spring:
  application:
    name: nova-dashboard-back-end
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DATABASE_URI}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
logging:
  file:
    path: var/log/
