spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        # enable_lazy_load_no_trans: true
    show-sql: true
    hibernate:
      ddl-auto: update
  docker:
    compose:
      stop:
        command: down
logging:
  level:
    org:
      springframework:
        security: trace
  file:
    path: var/log/
