spring:
  application:
    name: nova-dashboard-back-end
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URL}
          jwk-set-uri: ${JWK_SET_URL}
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          cognito-domain: ${COGNITO_DOMAIN}
security:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
