name: Formatting, Linting and Build
on: pull_request
jobs:
  formatting-linting-and-build:
    name: Formatting, Linting and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 22
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2
      - name: Build
        run: ./gradlew build
      - name: Post Checkstyle Results
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: 'build/reports/checkstyle/*.xml'
      - name: Post PMD Results
        uses: jwgmeligmeyling/pmd-github-action@master
        with:
          path: 'build/reports/pmd/*.xml'
      - name: Post SpotBugs Results
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: 'build/reports/spotbugs/*.xml'
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nova-dashboard-back-end-artifacts
          path: build/libs
